[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "res2eaf"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "prettytable>=3.17.0",
    "pympi-ling>=1.71",
    "webvtt-py>=0.5.1",
]

[project.scripts]
res2eaf = "res2eaf.__main__:main"


[tool.setuptools.packages.find]
where=["./src"]